/**
 * Old card name → new unique name.
 * Goal: break repetitive Ember/Hearth/Ashford/Iron/Canopy/Scalefen/etc. prefixes.
 * Ability names are unchanged (Hearthfort Aegis, Canopy Veil, …).
 */
export const RENAMES = {
  // ─── Human units ───
  'Ashford Crossbow': 'Quarryside Crossbows',
  'Ashford Heavy Guard': 'Bastion Wardens',
  'Ashford Longspear': 'Tollgate Longspears',
  'Ashford Outrider': 'Marchland Outriders',
  'Ashford Pike': 'Fencepost Pikes',
  'Ashford Shieldwall': 'Gatebrace Line',
  'Covenant Field Gun': 'Ordnance Culverin',
  'Covenant Halberd': 'Oathbill Halberdiers',
  'Covenant Lancer': 'Votive Lancers',
  'Covenant Skybreaker': 'Aegis Skybreaker',
  'Covenant Trebuchet': 'Siege Psalm',
  'Covenant Warhound Pack': 'Oathbound Hounds',
  'Ember Lance Column': 'Cinderlance Cohort',
  'Ember Pike Row': 'Redpike Line',
  'Ember Siege Ram': 'Brandram',
  'Ember War Dog': 'Sparkmastiffs',
  'Hearth Ballista': 'Homeguard Ballista',
  'Hearth Colossus Mammoth': 'Hearthfall Colossus',
  'Hearth Greatsword': 'Cleaving Oathsworn',
  'Hearth Gryphon Rider': 'Ridgewind Rider',
  'Hearth Longbow': 'Warmarch Longbows',
  'Hearth Militia': 'Parish Levy',
  'Hearth Slinger': 'Market Slingers',
  'Hearth Tusker': 'Stockyard Tusker',
  'Hearth Vanguard': 'Firstfire Vanguard',
  'Hearth War Engine': 'Gearworks Engine',
  'Hearthguard': 'Keepguard',
  'Iron Breaker': 'Platebreakers',
  'Iron Cohort': 'Lockstep Cohort',
  'Iron Column Veteran': 'Column Veterans',
  'Iron Covenant Banner': 'Oathstandard',
  'Iron Hearth Champion': 'Anvil Champion',
  'Iron Lance Rider': 'Spur Lancers',
  'Iron Sky Lancer': 'Skypike Lancers',
  'Iron Volley': 'Boltstorm Company',
  'Iron War Mammoth': 'Siege Mammoth',
  'Shieldborne': 'Shieldkin',
  'Stone Hearth Guard': 'Keystone Guard',
  'Thunderhoof Scout': 'Dusthorn Scouts',
  'War Mammoth': 'Grand Tusker',

  // ─── Human officers ───
  'Ashford Drill': 'Cadence Drillmaster',
  'Banner Hearth': 'Flamebanner Bearer',
  'Hearthline Quarter': 'Quartermaster Vale',
  'Iron Column Guide': 'Column Cartographer',
  'Mammoth Trail Handler': 'Tuskline Handler',
  'Shieldborne Tutor': 'Shieldkin Tutor',

  // ─── Demon units ───
  'Ashpit Boneflayer': 'Ashen Boneflayer',
  'Ashpit Skitter': 'Cinder Skitter',
  'Ashpit Tormentor': 'Ash Tormentor',
  'Ashwrought Infernal': 'Furnace Infernal',
  'Ashwrought Inferno Ram': 'Inferno Ram',
  'Brimclaw Hellcharger': 'Hellcharger',
  'Brimclaw Imp': 'Brim Imp',
  'Brimclaw Swarm': 'Impstorm',
  'Brimstone Hellknight': 'Brim Hellknight',
  'Brimstone Piker': 'Sulfur Piker',
  'Brimstone Pit Crawler': 'Brim Crawler',
  'Doomchain Abyssblade': 'Abyssblade',
  'Doomchain Cultist': 'Chain Cultist',
  'Doomchain Flayer': 'Chain Flayer',
  'Doomforge Abyssal': 'Abyssal Forgeborn',
  'Doomforge Hellblade': 'Hellblade',
  'Ember Rain Cultist': 'Emberfall Cult',
  'Ember Spitter': 'Magma Spitter',
  'Ember Tyrant Spawn': 'Tyrant Spawn',
  'Emberpit Bombardier': 'Soulpit Bombardier',
  'Emberpit Soulburner': 'Soulburner',
  'Hellgate Hound': 'Gate Hound',
  'Hellgate Marauder': 'Gate Marauder',
  'Hellgate Siege Engine': 'Gatebreak Engine',
  'Scorchvein Flamecaller': 'Vein Flamecaller',
  'Scorchvein Hellhound Pack': 'Vein Hellhounds',
  'Scorchvein Raider': 'Vein Raider',
  'Voidclaw Doomherald': 'Doomherald',
  'Voidclaw Horror': 'Void Horror',
  'Voidclaw Pit Beast': 'Clawed Pit Beast',
  'Voidpit Abomination': 'Void Abomination',
  'Voidpit Nightmare': 'Nightmaw',
  'Voidpit Stalker': 'Umbral Stalker',

  // ─── Demon officers ───
  'Ashpit Handler': 'Ash Handler',
  'Brimclaw Overseer': 'Imp Overseer',
  'Doomchain Handler': 'Chain Warden',
  'Emberpit Overseer': 'Soulpit Overseer',
  'Hellgate Sentry': 'Gate Sentry',
  'Scorchvein Guide': 'Vein Guide',
  'Voidpit Watcher': 'Umbral Watcher',

  // ─── Elf units ───
  'Canopy Archer': 'Leafcrown Archers',
  'Canopy Dryad Circle': 'Dryad Circle',
  'Canopy Glider': 'Glidersilk',
  'Canopy Longbow': 'Boughlong Archers',
  'Canopy Sniper': 'Quietbranch Sniper',
  'Canopy Spirit Hawk': 'Spirit Hawk',
  'Gale Archery Circle': 'Windbow Circle',
  'Gale Featherblade': 'Featherblade',
  'Gale Runner': 'Zephyr Runner',
  'Gale Windcaller': 'Windcaller',
  'Galewood Wisp Swarm': 'Galewood Wisps',
  'Leafwhisper Skirmisher': 'Whisperleaf Skirmisher',
  'Moonfall Spirit Archer': 'Spiritbow of Moonfall',
  'Moonlit Bladedancer': 'Silverstep Dancer',
  'Moonlit Shadow': 'Lunashade',
  'Moonlit Stalker': 'Nightstem Stalker',
  'Rootguard': 'Barkwarden',
  'Rootline Keeper': 'Leyline Keeper',
  'Rootline Skirmish Line': 'Briar Skirmish Line',
  'Rootweave Druid': 'Mossweave Druid',
  'Rootweave Treant': 'Elder Treant',
  'Starbough Greatbow': 'Constellation Greatbow',
  'Starbough Hunter': 'Startrail Hunter',
  'Starfall Ancient': 'Fallen Star Ancient',
  'Starfall Hawk Rider': 'Hawk of Starfall',
  'Verdant Briar Patch': 'Living Briar Patch',
  'Verdant Spear': 'Greenspire Spears',
  'Verdant Treant Sapling': 'Treant Sapling',
  'Verdant Wild Hunt': 'Wild Hunt Riders',
  'Verdant Wolf Pack': 'Grove Wolf Pack',

  // ─── Elf officers ───
  'Canopy Signal': 'Leafsignal',
  'Leafwhisper Liaison': 'Beastwhisper Liaison',
  'Moonlit Spotter': 'Moonspotter',
  'Rootline Watcher': 'Ley Watcher',
  'Starbough Tracker': 'Startrail Tracker',
  'Verdant Signal': 'Greensignal',

  // ─── Lizardman units ───
  'Basalt Coil Priest': 'Coil Priest',
  'Basalt Coil Serpent': 'Coil Serpent',
  'Basalt Gorgon': 'Stonegaze Gorgon',
  'Basalt Hydra Brood': 'Obsidian Hydra Brood',
  'Basalt World Serpent': 'Worldcoil Serpent',
  'Bogscale Javelin': 'Bog Javelins',
  'Bogscale Mire Beast': 'Mire Beast',
  'Bogscale Shieldwall': 'Mudbrace Line',
  'Bogscale Spear': 'Bog Spears',
  'Bogscale Temple Guard': 'Temple Scale Guard',
  'Crocodile Deathroll': 'Deathroll',
  'Crocodile Pit Fighter': 'Arena Croc',
  'Crocodile Titan': 'River Titan',
  'Mirepath Croc': 'Pathcroc',
  'Mirepath Gorgon Eye': 'Gorgon Eye',
  'Mirepath Naga': 'Mire Naga',
  'Mirepath Scout': 'Silt Scout',
  'Mirepath Stalker': 'Silt Stalker',
  'Scalefen Basilisk': 'Fen Basilisk',
  'Scalefen Brute': 'Scale Brute',
  'Scalefen Hunter': 'Fenbow Hunter',
  'Scalefen Ripper': 'Tide Ripper',
  'Scalefen Spawning Pool': 'Spawning Pool',
  'Scalefen Spitter': 'Venom Spitter',
  'Scalehide Ambusher': 'Camo Ambusher',
  'Scalehide Chameleon': 'Chameleon Warden',
  'Scalehide Skink': 'Dart Skink',
  'Swamp Gorgon Matriarch': 'Swamp Matriarch',
  'Swamp Lurker': 'Mire Lurker',
  'Swampstone Crusher': 'Stonejaw Crusher',
  'Swampstone Guard': 'Marshstone Guard',
  'Swampstone Pillar': 'Marshstone Pillar',
  'Viperfang Stalker': 'Fang Stalker',
  'Vipernest Brood': 'Viper Brood',
  'Vipernest Slinger': 'Fang Slinger',

  // ─── Lizardman officers ───
  'Basalt Coil Handler': 'Coil Handler',
  'Bogscale Handler': 'Bog Handler',
  'Crocodile Pit Handler': 'Arena Handler',
  'Hydra Nest Watcher': 'Brood Watcher',
  'Mirepath Watcher': 'Silt Watcher',
  'Scalefen Guide': 'Fen Guide',
  'Swampstone Guide': 'Marshstone Guide',
  'Vipernest Liaison': 'Brood Liaison',
}
