/**
 * Unique flavor text for Command Warfare cards.
 * Commanders already have handcrafted lines — omitted here.
 */
export const FLAVOR = {
  "Abyssal Forgeborn": "Forged where mercy failed quality control.",
  "Abyssblade": "The blade drinks light and pays in screams.",
  "Aegis Skybreaker": "When the sky needs breaking, call covenant.",
  "Anvil Champion": "Champion by title. Anvil by personality.",
  "Arena Croc": "Arena rules: there are no arena rules.",
  "Arena Handler": "The pit is deep. His patience is deeper.",
  "Ash Handler": "He counts the embers like beads on a prayer string.",
  "Ash Tormentor": "It does not cast spells. It reminds you of them.",
  "Ashen Boneflayer": "It peels armor the way gossip peels reputations.",
  "Ashwrought Berserker": "Calm is a rumor it has never believed.",
  "Barkwarden": "Bark for armor. Sap for stubbornness.",
  "Bastion Wardens": "They hold the door. The door holds civilization.",
  "Beastwhisper Liaison": "Beasts listen when she forgets to speak softly.",
  "Bog Javelins": "Throws sticks. Catches respect.",
  "Boltstorm Company": "A conversation in bolt-form.",
  "Boughlong Archers": "The string remembers every name it has erased.",
  "Brandram": "Slow, loud, and historically persuasive.",
  "Briar Skirmish Line": "A living hedge with a spear hobby.",
  "Brim Imp": "Cute, if you enjoy being bitten by punctuation.",
  "Brood Liaison": "He negotiates with nests. The nests negotiate back.",
  "Brood Watcher": "Count the heads. Then count again. Then run.",
  "Cacodemon Floater": "It drifts. Your courage does not.",
  "Cacodemon Wretch": "Wings like torn parchment; laughter like knives.",
  "Cadence Drillmaster": "Left, left, left-right-left — until fear marches too.",
  "Camo Ambusher": "Was a bush. Became a problem.",
  "Chain Warden": "The chain does not bind the foe. It binds the vow.",
  "Chameleon Warden": "Present. Absent. Suddenly teeth.",
  "Cinder Marauder": "Raids first, asks the ashes later.",
  "Cinder Skitter": "Too small to honor. Too fast to ignore.",
  "Cinderlance Cohort": "Lances lit. Horses committed.",
  "Cinderlash Fiend": "Every swing throws sparks like insults.",
  "Cinderlash Handler": "Where he points, the brushfire learns manners.",
  "Clawed Pit Beast": "Trample is how it says hello.",
  "Cleaving Oathsworn": "One blade. Several opinions. All loud.",
  "Cohort Standard": "The pole is oak. The oath is iron.",
  "Coil Handler": "Coil once for warning. Twice for supper.",
  "Coil Priest": "Prays in stone. Answers in venom.",
  "Coil Serpent": "A rope that decided to have hobbies.",
  "Column Cartographer": "He draws the map in chalk and certainty.",
  "Column Veterans": "Has seen worse. Will make you see it too.",
  "Constellation Greatbow": "When stars align, walls reconsider.",
  "Dart Skink": "Small, swift, and socially unimpressed.",
  "Deathroll": "A hug that rewrites anatomy.",
  "Doom Cultist": "Faith is optional. The chain is not.",
  "Doomherald": "It announces endings. Attendance is mandatory.",
  "Dryad Circle": "They heal the grove and bill the invaders.",
  "Dusthorn Scouts": "Hooves announce the news before the rider.",
  "Elder Treant": "Slow to anger. Impossible to hurry.",
  "Emberfall Cult": "They pray upward. The answers fall burning.",
  "Embertrail Raider": "Fast enough to steal; mean enough to keep.",
  "Fallen Star Ancient": "Fell once from the sky. Liked it here.",
  "Fang Slinger": "Pebbles dipped in bad ideas.",
  "Fang Stalker": "Venom with a calendar and a plan.",
  "Featherblade": "Steel and pinion in the same argument.",
  "Fen Basilisk": "Stare contest champion. Undefeated.",
  "Fen Guide": "Wade where he wades. The fen forgives him.",
  "Marsh Naga": "Poisoned courtesy with excellent reach.",
  "Fenbow Hunter": "Hunts from the reed line. Collects rumors.",
  "Fencepost Pikes": "The classic: long stick, short conversation.",
  "Firstfire Vanguard": "First through the door. Last to apologize.",
  "Flamebanner Bearer": "As long as the banner burns, the line does not break.",
  "Flamecaller": "The vein opens. The sky learns orange.",
  "Furnace Infernal": "A walking furnace with opinions about walls.",
  "Gale String": "She tunes the wind until the arrows hum in key.",
  "Galewood Wisps": "Pretty lights. Terrible decisions.",
  "Gatebrace Line": "Shields kiss. Enemies learn manners.",
  "Gatebreak Engine": "Wheels greased with dread; payload negotiable.",
  "Gearworks Engine": "Gears, oaths, and a very large crank.",
  "Glidersilk": "Wings of leaf-silk; attitude of a hawk.",
  "Gorgon Acolyte": "Still practicing the stare. Already effective.",
  "Gorgon Eye": "One eye. Many regrets.",
  "Grand Tusker": "War, but bigger and smellier.",
  "Greensignal": "Green smoke means hope. Green fire means hurry.",
  "Greenspire Spears": "Green wood. Red results.",
  "Grove Wolf Pack": "They do not howl for fun. They howl for lunch.",
  "Hawk of Starfall": "Rider and hawk share one appetite for height.",
  "Hearthfall Colossus": "The hearth, but make it tectonic.",
  "Hellblade": "Still hot from the anvil. Still angry about it.",
  "Hellcharger": "Hooves like hammers; brimstone like applause.",
  "Hellgate Sentry": "Nothing crosses the gate without leaving a name.",
  "Hellhound Pack": "They hunt as one appetite with many mouths.",
  "Hellknight": "Its armor smells like last week’s battlefield.",
  "Hellknight Aspirant": "Practice fear until it becomes a resume.",
  "Homeguard Ballista": "Home defense, if home includes a fortress.",
  "Hydra Hatchling": "Cute. Temporary. Multiplying.",
  "Hydra Spawn": "Sibling rivalry with cleaving.",
  "Imp Overseer": "The whip cracks; the imps remember who feeds them.",
  "Impstorm": "One imp is a nuisance. A swarm is a weather event.",
  "Inferno Ram": "Doors are a suggestion. Fire is a conclusion.",
  "Keepguard": "Guards the hearth. Judges your posture.",
  "Keystone Guard": "Stone for skin. Warmth for motive.",
  "Leafblade Duelist": "One cut. One bow. No encore needed.",
  "Leafcrown Archers": "From the leaves, every helmet looks like a request.",
  "Leafsignal": "Two flashes mean advance. Three mean the moon agrees.",
  "Ley Watcher": "The roots tell her who stepped wrong an hour ago.",
  "Leyline Keeper": "Keeps the line. Also keeps score.",
  "Link Flayer": "It runs so the wound can keep up.",
  "Lith Guard": "Hard as rock. Soft on nothing.",
  "Lith Pillar": "A wall that grew a badge and a glare.",
  "Living Briar Patch": "Do not sit. Do not stand. Do not exist nearby.",
  "Lockstep Cohort": "They do not advance. They insist.",
  "Lunashade": "A silhouette that learned to bite.",
  "Magma Spitter": "Ranged combat, if you count molten manners.",
  "Marchland Outriders": "Scout, courier, and occasional hurricane.",
  "Market Slingers": "Pebbles with patriotism.",
  "Marsh Spears": "Simple tool. Complicated aftermath.",
  "Marshstone Guide": "Stone that grew up in water still remembers teeth.",
  "Mawhound": "It was a dog once. Hell edited the draft.",
  "Mire Beast": "Mud with a pulse and a diet plan.",
  "Mire Lurker": "Half submerged. Fully committed.",
  "Moonfall Owl": "Night shift supervisor with a beak.",
  "Moonspotter": "If she sees you, the night already chose a side.",
  "Mossweave Druid": "Speaks tree. Trees speak back louder.",
  "Muck Stalker": "Leaves no footprints. Leaves plenty of panic.",
  "Mud Handler": "He speaks crocodile. The crocs pretend not to.",
  "Mudbrace Line": "Shields slick with swamp and resolve.",
  "Nightmaw": "You wake up. It does not.",
  "Nightstem Stalker": "Hides in silver. Strikes in certainty.",
  "Oathbill Halberdiers": "Axe, hook, and a firm opinion about cavalry.",
  "Oathbound Hounds": "Loyalty with teeth and a work ethic.",
  "Oathstandard": "Where it plants, courage files paperwork.",
  "Obsidian Hydra Brood": "Family reunion with extra necks.",
  "Ordnance Culverin": "Doctrine delivered at high velocity.",
  "Parish Levy": "Farmers yesterday. Heroes by lunch.",
  "Pathcroc": "The path is the croc. Watch your ankles.",
  "Pike Row Instructor": "Elbows in. Points out. Prayers optional.",
  "Platebreakers": "Breaks lines the way winters break rivers.",
  "Quarryside Crossbows": "Bolts stamped with civic pride and bad news.",
  "Quartermaster Vale": "Quarters, rations, and who sleeps with a spear.",
  "Quietbranch Sniper": "You will not hear the shot. The forest will.",
  "Redpike Line": "They flank like accountants with spears.",
  "Reed Scout": "Maps the mud. Mud maps the scouts.",
  "Ridgewind Rider": "Dinner conversation at altitude.",
  "River Titan": "When the river stands up, evacuate.",
  "Rootbound Ent": "Older than your kingdom. Less patient.",
  "Scale Brute": "Subtlety is for thinner lizards.",
  "Scorch Guide": "Follow the heat shimmer. Ignore the screaming.",
  "Scorchfiend Brute": "It does not pick targets. It picks neighborhoods.",
  "Scorchfiend Ravager": "Cleave now; apologize never.",
  "Shieldkin": "Born under a shield. Raised under orders.",
  "Shieldkin Tutor": "Raise the shield like you mean to keep your face.",
  "Siege Mammoth": "Siege engine that breathes and sulks.",
  "Siege Psalm": "Throws rocks. Also throws policy.",
  "Silt Watcher": "If the mud bubbles, do not ask why. Move.",
  "Silverstep Dancer": "Dance first. Then explain the blood.",
  "Skypike Lancers": "Lances from above. Gravity helps.",
  "Soulburner": "It cooks souls medium-rare and proud of it.",
  "Soulpit Bombardier": "Trajectory is faith. Impact is theology.",
  "Soulpit Overseer": "He stirs the pit until the ash starts answering.",
  "Sparkmastiffs": "Finds the soft target. Marks it. Smiles.",
  "Spawning Pool": "Where the fen writes new arguments.",
  "Spirit Hawk": "A prayer with talons and excellent eyesight.",
  "Spiritbow of Moonfall": "Arrows woven from moonlight and grudges.",
  "Spur Lancers": "Iron manners. Soft landing optional.",
  "Startrail Hunter": "Hunts by constellation and coincidence.",
  "Startrail Tracker": "He tracks by starlight and unfinished stories.",
  "Starwing Falcon": "A comma in the sky that ends sentences.",
  "Stockyard Tusker": "Friendly until stepped on. Then geology.",
  "Stonegaze Gorgon": "Look away. Then look away harder.",
  "Stonejaw Crusher": "Turns terrain into punctuation.",
  "Sulfur Crawler": "It arrives belly-first and leaves poison behind.",
  "Sulfur Piker": "The pike is long. The grin is longer.",
  "Swamp Hydra": "The swamp’s way of saying “enough.”",
  "Swamp Matriarch": "Mother of stares. Queen of quiet dread.",
  "Temple Scale Guard": "Guards the temple. Taxes the unworthy.",
  "Thornbite Scout": "Reports back. Usually with someone else’s blood.",
  "Thornclaw Sabertooth": "Beauty, fangs, and zero interest in diplomacy.",
  "Thornheart Stag": "Charges like a sermon with antlers.",
  "Thornpath Guide": "The path is narrow. The thorns are editorial.",
  "Thornspike Trapline": "The ground looks friendly. It is lying.",
  "Thornspire Unicorn": "Horn first. Questions never.",
  "Thornwall Sentinel": "A wall that grew a pulse and a grudge.",
  "Tide Ripper": "Rip first. Ask the fen later.",
  "Tollgate Longspears": "A polite way to keep the world at arm’s length.",
  "Treant Sapling": "Small tree. Large future problems.",
  "Tuskline Handler": "If the tusks turn, everyone turns. No debate.",
  "Tyrant Spawn": "Born mid-roar. Has not stopped since.",
  "Umbral Stalker": "Silence with claws and a hobby.",
  "Umbral Watcher": "He watches the dark so the dark does not watch you.",
  "Venom Spitter": "Range is a courtesy. Poison is the point.",
  "Viper Brood": "A nest that learned teamwork.",
  "Viperfang Hydra": "Heads for every flavor of misfortune.",
  "Void Abomination": "Stitched from leftovers that refused to stay dead.",
  "Void Horror": "If it looks at you twice, rewrite your will.",
  "Votive Lancers": "Pointed diplomacy on four legs.",
  "Warmarch Longbows": "Keeps the home fires… over there.",
  "Whisperleaf Skirmisher": "Steps softer than second thoughts.",
  "Wild Hunt Riders": "The forest goes riding. Bring a will.",
  "Windbow Circle": "They shoot as a single breath of wind.",
  "Windcaller": "She asks the air to misbehave. It obliges.",
  "Worldcoil Serpent": "The horizon that bites back.",
  "Zephyr Runner": "Arrives before the warning finishes forming.",
}
